"""Create cities and temperatures

Revision ID: 9ce6442b4434
Revises: 
Create Date: 2026-10-08 23:38:19.763545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce6442b4434'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities'))
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_temperatures_city_id_cities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temperatures'))
    )
    with op.batch_alter_table('temperatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temperatures_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temperatures_date_time'), ['date_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temperatures_date_time'))
        batch_op.drop_index(batch_op.f('ix_temperatures_city_id'))

    op.drop_table('temperatures')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))

    op.drop_table('cities')
    # ### end Alembic commands ###
